project_name: go-caniuse
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: main.go
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=0

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  files:
    - README.md
    - LICENSE
